### ISSUE TITLE
Remove algron references

### ISSUE THREAD

**Issue by garyservin** [ekumenlabs/roscpp_android#24]
There are still some libraries that point to the algron repos. Also, this repo is a fork of the algron one.
```
grep -Hrn --exclude-dir=output "algron" .                                        
    ./ndk.rosinstall:771:    uri: https://github.com/algron/rospack.git
    ./get_library.sh:26:    URL=https://github.com/algron/Boost-for-Android.git
```

**Comment by carlosjoan91** [comment]
I've been trying to build the sample app from the ROS Android NDK tutorial, however do_docker.sh fails as it tries to run get_library, since the algron repo is now non-existant. Is there a different repo for Boost-for-Android that I can switch this to? Or has this been otherwise solved?

**Comment by garyservin** [comment]
Hi @carlosjoan91! Thanks for reporting the issue, I've already created a PR to fix the issue and point to our own repos. It will be merged later today.
