### ISSUE TITLE
Does the rosndk support ros plugin?

### ISSUE THREAD

**Issue by balckgold** [ekumenlabs/roscpp_android#38]
Hi,I have a project that use the image_transport package on android ndk. and i builded it success follow this page
http://wiki.ros.org/android_ndk

But when i run it on my android device, it throw those errors:
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): [rospack] Warning: no such package image_transport
I/stderr  (10599): terminate called after throwing an instance of 'image_transport::Exception'
I/stderr  (10599):   what():  No plugins found! Does `rospack plugins --attrib=plugin image_transport` find any packages?

I am sure that I have linked the image_transport package in this project.but i am not sure if there are any plugin.  

So,Does the rosndk support ros plugin?

**Comment by ernestmc** [comment]
@balckgold your question is very timely. We are in the final stages of integrating support for plugins in the android build. You can check the development branch in my fork https://github.com/ernestmc/roscpp_android/tree/pluginlib
It would be great if you could help us test it once it's ready.

**Comment by ernestmc** [comment]
@balckgold I have submitted the pull-request #44 adding support for pluginlib. It would be great if you could test it and help validate it.

**Comment by ernestmc** [comment]
Pluginlib support has been added. You can find a tutorial explaining how to use it here:
http://wiki.ros.org/android_ndk/Tutorials/UsingPluginlib
