### ISSUE TITLE
Nodelets

### ISSUE THREAD

**Issue by nwotero** [ekumenlabs/roscpp_android#40]
Does this currently support nodelets or are they still in development like pluginlib?

**Comment by ernestmc** [comment]
@nwotero the nodelets package depends on pluginlib to dynamically load the nodelets. Once we have pluginlib working we'll be testing nodelets.

**Comment by nwotero** [comment]
Great, thank you!

**Comment by ernestmc** [comment]
@nwotero I have submitted the pull-request #44 adding support for pluginlib. It would be great if you could help test it and also check if nodelets works or further modifications need to be done.

**Comment by nwotero** [comment]
I can do that. Thanks for the heads up.

**Comment by nwotero** [comment]
This is what I got from my build:

> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- libs/poco-1.6.1/Foundation/include/Poco/SharedLibrary.h
> |+++ libs/poco-1.6.1/Foundation/include/Poco/SharedLibrary.h
> --------------------------
> File to patch: 
> Skip this patch? [y] y
> Skipping patch.
> 1 out of 1 hunk ignored
> can't find file to patch at input line 16
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- libs/poco-1.6.1/Foundation/src/SharedLibrary.cpp
> |+++ libs/poco-1.6.1/Foundation/src/SharedLibrary.cpp
> --------------------------
> File to patch: y
> y: No such file or directory
> Skip this patch? [y] y
> Skipping patch.
> 1 out of 1 hunk ignored
> patching file libs/poco-1.6.1/Foundation/src/SharedLibrary_ANDROID_STATIC.cpp
> patching file libs/poco-1.6.1/build/config/Android_static
> patch unexpectedly ends in middle of line
> patch: **** malformed patch at line 241:  
> 
> patching file catkin_ws/src/pluginlib/include/pluginlib/class_loader_imp.h
> patch unexpectedly ends in middle of line

I do have a libs/poco-1.6.1 directory but it doesn't have the files the build mentions that it is missing.

**Comment by ernestmc** [comment]
Thanks for your report. We are checking and will get back to you.

**Comment by ernestmc** [comment]
Hi @nwotero !
Sorry for the delay. We've been working on fixing this and there are new updates that will hopefully get everything working. It would be great if you could try it and give us your feedback. You should build everything from scratch since we had to modify the building of some libraries. There is now a sample app so you can test pluginlib right away.
Pull request is #44

**Comment by nwotero** [comment]
Hi @ernestmc 

The code compiled successfully! The one exception being that the link for libxml2 doesn't seem to work. I changed it to http://xmlsoft.org/sources/libxml2-2.9.1.tar.gz and it worked fine.

The pluginlib_sample_app doesn't seem to do anything, and move_base still has the patches to remove the need for pluginlib. Is there actually anything here to test, or should I write my own code to test it?

Thanks for your help!

**Comment by ernestmc** [comment]
@nwotero ,
Thank you so much for taking the time to test this. I'm glad to hear the build was successful. The `pluginlib_sample_app` only prints output through logcat. You should run the following command:
```
$ adb logcat | grep PLUGIN_TEST
```
And get this output:
```
D/PLUGIN_TEST( 6097): Starting app.
D/PLUGIN_TEST( 6097): Triangle area: 43.30
D/PLUGIN_TEST( 6097): Square area: 100.00
```

**Comment by nwotero** [comment]
Yes, I got that output. Seems like everything is working well!

**Comment by ernestmc** [comment]
Awesome! This proves that the support for pluginlib actually works! :tada:
We'll be merging this to the master soon and I'll be writing the documentation explaining how it works and how to use it.
In theory it should now be possible to enable nodelet support, although it might not be a straight forward process. If you want to go ahead and try it, it would be great.

**Comment by nwotero** [comment]
I certainly will, I will report back how well it goes. Might take a while though, as I have other tasks on my todo list, but hopefully by the week after next.

**Comment by ernestmc** [comment]
:ok_hand:

**Comment by ernestmc** [comment]
@nwotero We have merged pluginlib support to master and I've written a small [tutorial](http://wiki.ros.org/android_ndk/Tutorials/UsingPluginlib) on how to use it. Hope you find it useful. All feedback is appreciated.

**Comment by ernestmc** [comment]
Hi @nwotero!
I'm very happy to announce that we have opened a pull-request adding nodelet support in #47 . It also adds a sample app to test it. As always your feedback is greatly appreciated.

**Comment by ernestmc** [comment]
Support for nodelet including an example application has been merged to master.
