### ISSUE TITLE
urdfdom_headers build failed

### ISSUE THREAD

**Issue by b51** [ekumenlabs/roscpp_android#50]
When I did command ./do_docker.sh, it went error and show these messages:

> Build files have been written to: /opt/roscpp_output/libs/urdfdom/build
[  6%] [ 13%] Building CXX object urdf_parser/CMakeFiles/urdfdom_model_state.dir/src/urdf_model_state.cpp.o
Building CXX object urdf_parser/CMakeFiles/urdfdom_model_state.dir/src/twist.cpp.o
[ 20%] [ 26%] Building CXX object urdf_parser/CMakeFiles/urdfdom_world.dir/src/pose.cpp.o
Building CXX object urdf_parser/CMakeFiles/urdfdom_model.dir/src/pose.cpp.o
In file included from /opt/roscpp_output/target/include/urdf_model/twist.h:44:0,
                 from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/twist.cpp:38:
/opt/roscpp_output/target/include/urdf_model/pose.h: In member function 'void urdf::Vector3::init(const string&)':
/opt/roscpp_output/target/include/urdf_model/pose.h:78:25: error: 'stod' is not a member of 'std'
In file included from /opt/roscpp_output/target/include/urdf_model/twist.h:44:0,
                 from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/twist.cpp:38:
/opt/roscpp_output/target/include/urdf_model/pose.h:90:42: error: 'to_string' is not a member of 'std'
make[2]: *** [urdf_parser/CMakeFiles/urdfdom_model_state.dir/src/twist.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 33%] Building CXX object urdf_parser/CMakeFiles/urdfdom_model.dir/src/model.cpp.o
In file included from /opt/roscpp_output/target/include/urdf_model_state/model_state.h:44:0,
                 from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:38:
/opt/roscpp_output/target/include/urdf_model/pose.h: In member function 'void urdf::Vector3::init(const string&)':
/opt/roscpp_output/target/include/urdf_model/pose.h:78:25: error: 'stod' is not a member of 'std'
In file included from /opt/roscpp_output/target/include/urdf_model_state/model_state.h:44:0,
                 from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:38:
/opt/roscpp_output/target/include/urdf_model/pose.h:90:42: error: 'to_string' is not a member of 'std'
In file included from /opt/roscpp_output/target/include/urdf_model_state/model_state.h:46:0,
                 from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:38:
/opt/roscpp_output/target/include/urdf_model_state/types.h: At global scope:
/opt/roscpp_output/target/include/urdf_model_state/types.h:48:9: error: 'shared_ptr' in namespace 'std' does not name a type
In file included from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:38:0:
/opt/roscpp_output/target/include/urdf_model_state/model_state.h:144:15: error: 'JointStateSharedPtr' was not declared in this scope
/opt/roscpp_output/target/include/urdf_model_state/model_state.h:144:34: error: template argument 1 is invalid
/opt/roscpp_output/target/include/urdf_model_state/model_state.h:144:34: error: template argument 2 is invalid
/opt/roscpp_output/target/include/urdf_model_state/model_state.h: In member function 'void urdf::ModelState::clear()':
/opt/roscpp_output/target/include/urdf_model_state/model_state.h:141:24: error: request for member 'clear' in '((urdf::ModelState*)this)->urdf::ModelState::joint_states', which is of non-class type 'int'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp: In function 'bool urdf::parseModelState(urdf::ModelState&, TiXmlElement*)':
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:76:35: error: aggregate 'boost::shared_ptr<urdf::JointState> joint_state' has incomplete type and cannot be defined
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:94:7: error: 'split' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:94:44: error: 'is_any_of' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:113:7: error: 'split' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:113:44: error: 'is_any_of' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:132:7: error: 'split' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:132:42: error: 'is_any_of' is not a member of 'boost'
/opt/roscpp_output/libs/urdfdom/urdf_parser/src/urdf_model_state.cpp:146:21: error: request for member 'push_back' in 'ms.urdf::ModelState::joint_states', which is of non-class type 'int'
make[2]: *** [urdf_parser/CMakeFiles/urdfdom_model_state.dir/src/urdf_model_state.cpp.o] Error 1
make[1]: *** [urdf_parser/CMakeFiles/urdfdom_model_state.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object urdf_parser/CMakeFiles/urdfdom_model.dir/src/link.cpp.o
In file included from /opt/roscpp_output/libs/urdfdom/urdf_parser/src/pose.cpp:38:0:
................

I built it on Ubuntu 14.04 64bit with g++ 4.8 and already update roscpp_android to the newest > 4dd3b667d7efe1857d32a80aa63fac3d8773923b version, but still got this error, and then I tried g++ 4.6, also no help.

Can anyone help me figure out this problem? Thank you.

**Comment by ernestmc** [comment]
Hi @b51. The latest version has fixed this problem. You should delete your `output` folder and build again. Let us know if that worked.

**Comment by b51** [comment]
OK, ernestmc , Thanks for your answer. I already deleted the roscpp_android folder which include the output folder, and git clone it from here again. I'm running do_docker.sh again, and it will take a long time downloading, so I will give you a reply at once when download and build done..

**Comment by b51** [comment]
Thanks @ernestmc , After long time download and build it finally worked, thanks for ur replay!

**Comment by ernestmc** [comment]
@b51 glad to hear it worked!
