### ISSUE TITLE
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

### ISSUE THREAD

**Issue by zzkzsmj** [ekumenlabs/roscpp_android#54]
I use the Ubuntu environment，Refer to the "ROS NDK How to cross-compile any other ROS package for Android" tutorial, compile sick_tim,./do_docker to sick_tim when I run the wrong as follows:
```
==> add_subdirectory(sick_tim)
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:106 (find_package_handle_standard_args)
  sick_tim/CMakeLists.txt:11 (find_package)
```

**Comment by gavanderhoorn** [comment]
Also: [Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)](http://answers.ros.org/question/251919) on ROS Answers.

**Comment by garyservin** [comment]
We currently don't support using PkgConfig with the ROS NDK, you will need to use a workaround to specify the correct variables for the library you need to use (in this case libusb). [Here's](https://github.com/ekumenlabs/roscpp_android/blob/master/patches/robot_pose_ekf.patch#L11) an example on how we do that for another package:

**Comment by ernestmc** [comment]
Hi @zzkzsmj as @garyservin said, adding the library dependency by hand is the way. Still you will need to crosscompile the libusb library for ARM. And even after that I'm not sure if the Android system will authorize permission to access the USB port resource. [This link](https://github.com/libusb/libusb/tree/master/android) might be useful.
Good luck and let us know if anything of this works!

**Comment by ernestmc** [comment]
Hi @zzkzsmj ! Were you able to make this work? Is it ok to close this issue?

**Comment by zzkzsmj** [comment]
HI@ernestmc Sorry, I have been back in the mail, forgot to reply here, the problem is not resolved, I am trying other methods, there will be a solution I will submit a solution.

**Comment by ernestmc** [comment]
Ok thanks for your reply @zzkzsmj . I'm going to close the ticket for now since it's not something directly related to the build environment but please do post your findings here once you have them. I feel this can be something very useful for the ROS on android community.
