### ISSUE TITLE
Pluginlib helper should use class name instead of lookup name

### ISSUE THREAD

**Issue by ernestmc** [ekumenlabs/roscpp_android#60]
If pluginlib lookup name is not defined, the use the class name.
As per the documentation:

> Legacy "Lookup Name"
Pre-Groovy versions of pluginlib required specifying a "lookup name" for exported classes in both the plugin description file and export macro. This lookup name acted as an alias for the true class name -- the true class name was not used in the user facing interface. The reason why this lookup alias was used instead of the real name was due to a technical limitation in older versions.

**Comment by jubeira** [comment]
Closed via #61 .
