### ISSUE TITLE
how can I complie my own c++ code to android?

### ISSUE THREAD

**Issue by gongyue666** [ekumenlabs/roscpp_android#69]
Hi, nowadays I want to move my own codes to Android.I move my codes to ~/ros-android-ndk/roscpp_android/out/catkin_ws/src/ and then run ./do_docker.sh. After that I get the output files in  ~/ros-android-ndk/roscpp_android/out/catkin_ws/devel/lib, but I see they are not in out/target/lib/, how can I do that in the right way?
another question: must I put all my c++ code in android project?how can I make the file structure?I am confused a lot now.I have follow the http://wiki.ros.org/android_ndk/Tutorials/WrappingNativeRosjavaNode, but when I using my own  c++ codes, it always see can not find somethings, for example: my own msg and so on.PLZ help I don't know how to do now.

**Comment by gongyue666** [comment]
hi , now I have successfully add new msgs to the docker. What I do is put the new msg's folder to ros-android-ndk/roscoo_android/output/catkin_make/src/ and run ./do_docker.sh.
But now when can compile my new node using the same method many errors coming.it says:
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot open crtbegin_dynamic.o: No such file or directory
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot open crtend_android.o: No such file or directory
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -lm
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -lc
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -ldl
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: CMakeFiles/docking_node.dir/src/node.cpp.o: in function _GLOBAL__sub_I_node.cpp:node.cpp(.text.startup+0x7c): error: undefined reference to '__dso_handle'
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: /opt/roscpp_output/catkin_ws/devel/lib/libroscpp.a(internal_timer_manager.cpp.o): in function boost::unique_lock<boost::mutex>::~unique_lock() [clone .constprop.49]:internal_timer_manager.cpp(.text._ZN5boost11unique_lockINS_5mutexEED2Ev.constprop.49+0xe): error: undefined reference to 'pthread_mutex_unlock'
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: /opt/roscpp_output/catkin_ws/devel/lib/libroscpp.a(internal_timer_manager.cpp.o): in function ros::TimerManager<ros::WallTime, ros::WallDuration, ros::WallTimerEvent>::TimerManager():internal_timer_manager.cpp(.text._ZN3ros12TimerManagerINS_8WallTimeENS_12WallDurationENS_14WallTimerEventEEC2Ev+0x16): error: undefined reference to 'pthread_mutex_init'
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: /opt/roscpp_output/catkin_ws/devel/lib/libroscpp.a(internal_timer_manager.cpp.o): in function ros::TimerManager<ros::WallTime, ros::WallDuration, ros::WallTimerEvent>::TimerManager():internal_timer_manager.cpp(.text._ZN3ros12TimerManagerINS_8WallTimeENS_12WallDurationENS_14WallTimerEventEEC2Ev+0x34): error: undefined reference to 'pthread_mutex_init'
/opt/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.gold: /opt/roscpp_output/catkin_ws/devel/lib/libroscpp.a(internal_timer_manager.cpp.o): in function ros::TimerManager<ros::WallTime, ros::WallDuration, ros::WallTimerEvent>::TimerManager():internal_timer_manager.cpp(.text._ZN3ros12TimerManagerINS_8WallTimeENS_12WallDurationENS_14WallTimerEventEEC2Ev+0x4e): error: undefined reference to 'pthread_mutex_init'
and other error logs that cannot find some libs.I delete most of my codes in new node only a empty class file and main.cpp left, but the error still be here.Is the way I add new pkg wrong? how to add my own new pkg to ros android ??

**Comment by ernestmc** [comment]
Hi @gongyue666 . To add a new ROS package to the build you should add it to the catkin workspace as usual. Make sure that your package builds correctly with catkin. There are two important things to take into account:
- Make sure your package dependencies are cross-compiled as well
- Take into account that the final result of the build is a static link of all resulting libraries in one single shared library. For this to work correctly you need to add the library corresponding to your package into [this line](https://github.com/ekumenlabs/roscpp_android/blob/master/files/Android.mk.move_base#L5). Beware that the libraries need to be in a certain order for the link to work. This is tricky and we haven't been able to automate it yet.

If none of the above works for you, you might want to check out [this newer version](https://github.com/Intermodalics/ros_android) of the cross-compile environment. It has a lot of updates and improvements. Let me know if this works!

**Comment by gongyue666** [comment]
hi, thx for your reply.
1  I don't want to make a app, now I have just test for compile the ros node, what I complie is only a node with nothing else, but it can not build. The node like this: 
main.cpp:
`
#include <docking_core.h>
#include <ros/ros.h>
int main(int argc ,char** argv)
{
	ros::init(argc, argv, "auto_docking");
	Docking auto_dock_("auto_docking");
	ros::spin();
  	return 0;
}
`
docking_core.h:
`#include <ros/ros.h>
#include <iostream>
#include <string>
class Docking{
public:
	Docking(std::string name){}
};
 `
as you see it really have nothing but a node.
2 should l add the line shlibs := *** in the Android.mk.move_base or make a new Android.mk.docking and copy the line shlibs := *** in it ? If I just want to compile the docking_node without making app, shoud I do this steps,too? 
3 do I add the new node in the right way? copy the new node's folder to /roscpp_android/output/catkin_make/src/ and the run do_docker.sh. is the right way?
4 I am downloading the new version, thx for your contribution!!

**Comment by gongyue666** [comment]
hi, I add the line shlibs := *** to  Android.mk.move_base and also make a new Android.mk.docking copy from Android.mk.move_base. The error still be here.

**Comment by gongyue666** [comment]
hi, when I install the new version many errors coming, I don't know what setting or configurations wrong.I have add a quesion under the new version.if you hava time, plz have a look, many thx!!!

**Comment by gongyue666** [comment]
The new version worked!!thx so much~
